<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Remy Beauregard, Department of Economics, UC Davis">

<title>ECN 102: Analysis of Economics Data</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="FinalFQ2024AK_files/libs/clipboard/clipboard.min.js"></script>
<script src="FinalFQ2024AK_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="FinalFQ2024AK_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="FinalFQ2024AK_files/libs/quarto-html/popper.min.js"></script>
<script src="FinalFQ2024AK_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="FinalFQ2024AK_files/libs/quarto-html/anchor.min.js"></script>
<link href="FinalFQ2024AK_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="FinalFQ2024AK_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="FinalFQ2024AK_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="FinalFQ2024AK_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="FinalFQ2024AK_files/libs/bootstrap/bootstrap-8ffd5f67044e5306d9846f29df41dda5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<meta name="description" content="Sample final exam answer key for ECN 102.">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="ECN 102 FQ 2024 Sample Final AK.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ECN 102: Analysis of Economics Data</h1>
<p class="subtitle lead">Final Exam FQ 2024 – Answer Key</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Remy Beauregard, Department of Economics, UC Davis </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div style="text-align: center">
<p>This exam consists of 5 short-answer questions (with sub-parts) and 5 multiple choice questions. You will have a maximum of 2 hours to complete this exam. No additional time may be taken without prior accommodation. Make sure to read every question thoroughly and carefully. Make sure to answer all parts of all questions completely and fully explain when asked. Show all work to receive full credit.</p>
<p>You may use only the calculators provided by the instructor. Graphing calculators, phone calculators, and other non-standard calculators may not be used. For questions requiring computation, it suffices to express your final answer with 2 significant figures.</p>
<p>There is a formula sheet and scratch paper provided at the end of this exam. You may remove these pages and discard them after the exam. If you plan to use any of these extra pages for your final answers, you must write your name and student ID at the top of each scratch page to ensure it is not lost.</p>
<p>This exam is worth 100 points.</p>
</div>
<p><strong>Solution Guide</strong></p>
<div style="page-break-after: always;"></div>
<p><strong>For this exam, we will use a dataset that includes annual salary, demographic characteristics, and other metrics for a sample of individuals. The variables present in the dataset are listed here, along with their format and labels.</strong></p>
<div class="cell" data-collectcode="true">
<div class="cell-output cell-output-stdout">
<pre><code>Contains data from SalaryCameron.dta
 Observations:           776                  Data for A. Colin Cameron (2022), ANALYSIS OF ECONOMIC DATA, Amazon
    Variables:            12                  22 Jan 2022 15:50
-----------------------------------------------------------------------------------------------------------------------------------------
Variable      Storage   Display    Value
    name         type    format    label      Variable label
-----------------------------------------------------------------------------------------------------------------------------------------
salary          float   %9.0g                 Annual Salary in dollars
lnsalary        float   %9.0g                 Natural Logarithm of Annual Salary
satverb         int     %32.0g                SAT test verbal score (highest self-reported score as of 2007)
satmath         int     %32.0g                SAT test mathematics score (highest self-reported score as of 2007)
highgrade       byte    %8.0g                 Highest grade ever completed
age             float   %9.0g                 Age in years
sex             byte    %14.0g                1 = female 0 = male
minority        float   %9.0g                 1 = minority 0 = not minority
height          float   %9.0g                 Height in inches
weight          int     %8.0g                 Weight in pounds
genhealth       byte    %9.0g                 Health status: 1=Excellent 2=VeryGood 3=Good 4=Fair 5=Poor
actscore        float   %32.0g                ACT test score (highest self-reported score as of 2007)
-----------------------------------------------------------------------------------------------------------------------------------------
Sorted by: 
     Note: Dataset has changed since last saved.</code></pre>
</div>
</div>
<section id="question-1-summary-statistics-16-points" class="level2">
<h2 class="anchored" data-anchor-id="question-1-summary-statistics-16-points">Question 1: Summary Statistics [16 points]</h2>
<ol type="a">
<li>Is this sample of data likely to be observational or experimental? Explain. [2 points]</li>
</ol>
<p><strong>Observational</strong>: no randomization is taking place, we are merely observing a sample of individuals.</p>
<ol start="2" type="a">
<li>Is this sample of data likely to be cross-section, time series, panel, or repeated cross-section? Explain. [2 points]</li>
</ol>
<p><strong>Cross-section</strong>: we observe different units of observation (people) at a single point in time; we have no <em>year</em>, <em>month</em>, <em>day</em> variable.</p>
<ol start="3" type="a">
<li>How else could we classify data for our variable <em>salary</em>? Explain. [2 points]</li>
</ol>
<p><strong>Numerical</strong> or continuous numerical.</p>
<ol start="4" type="a">
<li>What type of <strong>variable</strong> is <em>minority</em> if we include it in a regression? Explain. [2 points]</li>
</ol>
<p>This is a <strong>dummy variable</strong> because it takes only values 1 or 0 if someone is or is not a minority.</p>
<ol start="5" type="a">
<li>Are any other <strong>variables</strong> the same type as our variable <em>minority</em> when used in regression? [2 points]</li>
</ol>
<p><em>Sex</em> is also a dummy variable that takes value 1 for female and 0 for male.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
      height |        776    67.68814    4.198084         50         83
      weight |        776    171.3015     43.5782         92        475
      salary |        776    36184.23    24426.81        300     130254</code></pre>
</div>
</div>
<ol start="6" type="a">
<li>Which variable above has the greatest dispersion? Which has the least? [3 points]</li>
</ol>
<p><span class="math display">\[CV_{height}=\frac{4.20}{67.69}=0.06\]</span></p>
<p><span class="math display">\[CV_{weight}=\frac{43.58}{171.30}=0.25\]</span></p>
<p><span class="math display">\[CV_{salary}=\frac{24426.81}{36184.23}=0.68\]</span></p>
<p><em>Salary</em> has the highest dispersion; <em>height</em> has the least.</p>
<ol start="7" type="a">
<li>What would we expect the standard error of <em>height</em> to be? What is this an estimator for? [3 points]</li>
</ol>
<p><span class="math display">\[se_{height}=\frac{4.20}{\sqrt{776}}=0.15\]</span></p>
<p>This is an estimator for the <strong>population standard deviation</strong> of the sample mean of <em>height</em>.</p>
</section>
<section id="question-2-bivariate-regression-16-points" class="level2">
<h2 class="anchored" data-anchor-id="question-2-bivariate-regression-16-points">Question 2: Bivariate Regression [16 points]</h2>
<p>Suppose we want to run a regression to predict <em>salary</em> using <em>age</em> with OLS.</p>
<ol type="a">
<li>Write down the population regression model we are trying to estimate. [2 points]</li>
</ol>
<p><span class="math display">\[\widehat{salary}=\beta_1+\beta_2age\text{ or}\]</span> <span class="math display">\[salary=\beta_1+\beta_2age+u\]</span></p>
<ol start="2" type="a">
<li>What will the <strong>homoskedasticity</strong> assumption imply for this regression? [2 points]</li>
</ol>
<p><span class="math inline">\(Var(u)=\sigma^2_u\)</span> or our errors have a constant variance across values of <em>age</em>.</p>
<ol start="3" type="a">
<li>What will the <strong>linearity</strong> assumption imply for this regression? [2 points]</li>
</ol>
<p>Our true population model is <span class="math inline">\(salary=\beta_1+\beta_2age+u\)</span> (we do not have any omitted covariates or nonlinear relationship).</p>
<ol start="4" type="a">
<li>Suppose we estimate this regression and find that our 95% confidence interval for <span class="math inline">\(b_2\)</span> is <span class="math inline">\((478.28,4733.39)\)</span>. What conclusion about our population coefficient <span class="math inline">\(\beta_2\)</span> on <em>age</em> does this imply? [3 points]</li>
</ol>
<p>Since 0 is not included in our 95% CI, we can reject the null for the test of association and conclude that <span class="math inline">\(\beta_2\neq0\)</span> or that <em>age</em> is associated with <em>salary</em>.</p>
<ol start="5" type="a">
<li>Suppose our R-squared for this regression is 0.0074. What does this mean in words? [2 points]</li>
</ol>
<p><span class="math inline">\(0.0074\times100=0.74\%\)</span> of the variation in <em>salary</em> is explained by <em>age</em>.</p>
<p>Suppose instead we estimated a regression of salary on the <strong>log of age</strong>.</p>
<ol start="6" type="a">
<li>What would we call this type of regression? [2 points]</li>
</ol>
<p>Linear-log regression</p>
<ol start="7" type="a">
<li>How would we interpret <span class="math inline">\(b_2\)</span> for this regression in words? [3 points]</li>
</ol>
<p>A 1% change in <em>age</em> is associated with a <span class="math inline">\(b_2/100\)</span>-unit (dollar) change in <em>salary</em>.</p>
</section>
<section id="question-3-multivariate-regression-23-points" class="level2">
<h2 class="anchored" data-anchor-id="question-3-multivariate-regression-23-points">Question 3: Multivariate Regression [23 points]</h2>
<p>We now estimate <span class="math inline">\(\widehat{salary}=\beta_1+\beta_2age+\alpha_1sex+\alpha_2(age\times sex)\)</span> with OLS and obtain the following:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      Source |       SS           df       MS      Number of obs   =       776
-------------+----------------------------------   F(3, 772)       =      4.32
       Model |  7.6433e+09         3  2.5478e+09   Prob &gt; F        =    0.0049
    Residual |  4.5478e+11       772   589087072   R-squared       =    0.0165
-------------+----------------------------------   Adj R-squared   =    0.0127
       Total |  4.6242e+11       775   596669065   Root MSE        =     24271

------------------------------------------------------------------------------
      salary | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
         age |   1706.862   1579.951     1.08   0.280    -1394.648    4808.373
         sex |  -53271.99   58521.46    -0.91   0.363    -168152.1    61608.08
     ageXsex |   1807.953   2165.534     0.83   0.404    -2443.081    6058.986
       _cons |  -7612.026   42668.87    -0.18   0.858    -91372.78    76148.73
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>(<strong>Hint</strong>: review variable descriptions on page 2)</p>
<ol type="a">
<li>What type of variable is <em>sex</em> in this regression? [2 points]</li>
</ol>
<p>Dummy variable</p>
<ol start="2" type="a">
<li>Interpret the value of <span class="math inline">\(b_2\)</span> in words. [2 points]</li>
</ol>
<p>Being one year older on average is <em>associated</em> with a $1706.86 higher salary for men (<span class="math inline">\(sex=0\)</span>).</p>
<ol start="3" type="a">
<li>Interpret the value of <span class="math inline">\(a_1\)</span> in words. [2 points]</li>
</ol>
<p>Women make, on average, $53,271.99 less than men (or the difference in intercept between men and women).</p>
<ol start="4" type="a">
<li>Interpret the value of <span class="math inline">\(a_2\)</span> in words. [2 points]</li>
</ol>
<p>Women make $1807.95 more for each additional year older they are compared to men. Being one year older is associated with a <span class="math inline">\(1706.86+1807.95=\$3514.81\)</span> higher salary for women (<span class="math inline">\(sex=1\)</span>) (or difference in slopes between men and women).</p>
<ol start="5" type="a">
<li>What conclusion should we draw from the reported F-statistic and its associated p-value? [3 points]</li>
</ol>
<p><span class="math inline">\(\Pr(F &gt; 4.32) = 0.0049 &lt; \alpha = 0.05\)</span>: reject the null hypothesis of the default test of overall significance. At least one of our regressors/our model explains variation in our outcome variable statistically significantly.</p>
<ol start="6" type="a">
<li>Which of our coefficients are statistically different from zero at <span class="math inline">\(\alpha=5\)</span>%? Which are not? [3 points]</li>
</ol>
<p>All regressors have a p-value above <span class="math inline">\(\alpha=0.05\)</span>: none are statistically significantly different from zero.</p>
<ol start="7" type="a">
<li>If our four population assumptions hold, how would we expect <span class="math inline">\(b_2\)</span> to be distributed? Your answer should take the form <span class="math inline">\(b_2\sim\_\_(\_\_,\_\_)\)</span>. Use Greek letters when appropriate. [3 points]</li>
</ol>
<p><span class="math display">\[b_2\sim N\left(\beta_2,\frac{\sigma^2_u}{\sum_{i=1}^n\tilde{x}_{2i}^2}\right)\text{ or }b_2\sim N(\beta_2,\sigma^2_{b_2})\]</span></p>
<ol start="8" type="a">
<li>Find an expression for the marginal effect of <em>age</em> in this regression. [3 points]</li>
</ol>
<p><span class="math display">\[\frac{\partial\widehat{salary}}{\partial age}=b_2+a_2sex\]</span></p>
<ol type="i">
<li>Why are our values for R-squared and Adj R-squared different in this regression? Why might we prefer one instead of the other for multivariate regressions? [3 points]</li>
</ol>
<p>Adjusted R-squared imposes a penalty for adding additional regressors, here <span class="math inline">\(k=4\)</span>, while regular R-squared does not. We may want a measure of model fit that penalizes endlessly adding regressors.</p>
</section>
<section id="question-4-hypothesis-testing-18-points" class="level2">
<h2 class="anchored" data-anchor-id="question-4-hypothesis-testing-18-points">Question 4: Hypothesis Testing [18 points]</h2>
<p>For a general multivariate OLS regression with sample size <span class="math inline">\(n\)</span>, <span class="math inline">\(k-1\)</span> regressors (<span class="math inline">\(x_2,...,x_k\)</span>) and a constant, and <span class="math inline">\(j=1,...,k\)</span> as our index of coefficients:</p>
<ol type="a">
<li>What are the null and alternate hypotheses for the default test of <strong>association</strong> for a single <span class="math inline">\(b_j\)</span>? [2 points]</li>
</ol>
<p><span class="math display">\[H_0:\beta_j=0\]</span> <span class="math display">\[H_A:\beta_j\neq0\]</span></p>
<ol start="2" type="a">
<li>Suppose we reject this null hypothesis for the default test of association for <span class="math inline">\(b_j\)</span> above. How would we interpret this conclusion in words? [4 points]</li>
</ol>
<p>There is a statistically significant association between the <strong>unique</strong> variation in our regressor <span class="math inline">\(x_j\)</span> and our outcome variable <span class="math inline">\(y\)</span>.</p>
<ol start="3" type="a">
<li>Name the two models that are compared when computing the statistic for the default test of <strong>overall significance</strong>. Write down the population model for both. [6 points]</li>
</ol>
<p><span class="math display">\[\text{Unrestricted: } \hat{y}=\beta_1+\beta_2x_x+...+\beta_kx_k\text{ ; Restricted:}\hat{y}=\beta_1+0+...0\]</span></p>
<ol start="4" type="a">
<li>If the p-value for the default test of association for <span class="math inline">\(b_j\)</span> is 0.035, what would we expect the p-value to be for an F-test of the single regressor <span class="math inline">\(b_j\)</span>? [3 points]</li>
</ol>
<p><span class="math inline">\(p=0.035\)</span> (the same as for the test of association)</p>
<ol start="5" type="a">
<li>If the t-statistic for the default test of association for <span class="math inline">\(b_j\)</span> is 2.12, what would we expect the F-statistic to be for an F-test of the single regressor <span class="math inline">\(b_j\)</span>? [3 points]</li>
</ol>
<p><span class="math inline">\(F=(t)^2=2.12^2=4.49\)</span> (the square of the t-statistic for the test of association)</p>
</section>
<section id="question-5-miscellaneous-17-points" class="level2">
<h2 class="anchored" data-anchor-id="question-5-miscellaneous-17-points">Question 5: Miscellaneous [17 points]</h2>
<ol type="a">
<li>If the default p-values reported for all coefficients from a multivariate regression of <span class="math inline">\(y\)</span> on <span class="math inline">\(x_2,...,x_k\)</span> are above 0.05 but we observe <code>Prob &gt; F = 0.035</code>, what can we conclude about our regressors? [4 points]</li>
</ol>
<p>All of our regressors are not statistically significantly different from zero <strong>individually</strong> but do <strong>jointly</strong> explain variation in our outcome variable.</p>
<ol start="2" type="a">
<li>What assumption or assumptions are we concerned may be violated if we choose to use <strong>robust</strong> standard errors in our regression? [3 points]</li>
</ol>
<p><strong>Homoskedasticity</strong> assumption (no explanation needed)</p>
<ol start="3" type="a">
<li>What assumption or assumptions are we concerned may be violated if we choose to use <strong>clustered</strong> standard errors in our regression? [3 points]</li>
</ol>
<p><strong>Independence</strong> and <strong>homoskedasticity</strong> assumptions (no explanation needed)</p>
<ol start="4" type="a">
<li>If we suspect but <strong>are not sure</strong> that our data is homoskedastic, what type of standard errors should we use? Are we concerned that doing so may lead to problems? Why or why not? [4 points]</li>
</ol>
<p>We should use <strong>robust standard errors</strong>. We are not concerned; using robust standard errors would not be wrong even if our data is homoskedastic; NOT using robust standard errors would be wrong if our data is NOT homoskedastic.</p>
<ol start="5" type="a">
<li>Compute the following sum [3 points]: <span class="math display">\[\sum_{i=2}^3(3i)^{i-1}-i\]</span></li>
</ol>
<p><span class="math display">\[\sum_{i=2}^3(3i)^{i-1}-i=6^{2-1}-2+9^{3-1}-3=6+81-5=82\]</span></p>
</section>
<section id="multiple-choice-2-points-each" class="level2">
<h2 class="anchored" data-anchor-id="multiple-choice-2-points-each">Multiple Choice [2 points each]</h2>
<p>Only one answer is correct for each question. Read carefully and choose the best possible answer.</p>
<section id="mc-1-and-2" class="level3">
<h3 class="anchored" data-anchor-id="mc-1-and-2">MC 1 and 2</h3>
<p>Suppose the probability of <strong>not</strong> rejecting <span class="math inline">\(H_0\)</span> is 0.95 when <span class="math inline">\(\beta_j=0\)</span> and 0.3 when <span class="math inline">\(\beta_j\neq0\)</span> for a test on OLS <span class="math inline">\(b_j\)</span>.</p>
<p>The <strong>power</strong> of this test will be equal to:</p>
<ol type="a">
<li><p>0.05</p></li>
<li><p>0.95</p></li>
</ol>
<p><strong>c) 0.7</strong></p>
<ol start="4" type="a">
<li>0.3</li>
</ol>
<p>The <strong>size</strong> of this test will be equal to:</p>
<p><strong>a) 0.05</strong></p>
<ol start="2" type="a">
<li><p>0.95</p></li>
<li><p>0.7</p></li>
<li><p>0.3</p></li>
</ol>
</section>
<section id="mc-3" class="level3">
<h3 class="anchored" data-anchor-id="mc-3">MC 3</h3>
<p>A trial judge says he believes he made a Type II error when sentencing a defendant. The precedent in court is that individuals are <strong>innocent until proven guilty</strong>. If the judge is correct, which of the following took place?</p>
<ol type="a">
<li>The defendant was truly guilty and was found guilty</li>
</ol>
<p><strong>b) The defendant was truly guilty but was found innocent</strong></p>
<ol start="3" type="a">
<li><p>The defendant was truly innocent and was found innocent</p></li>
<li><p>The defendant was truly innocent but was found guilty</p></li>
</ol>
</section>
<section id="mc-4" class="level3">
<h3 class="anchored" data-anchor-id="mc-4">MC 4</h3>
<p>If <span class="math inline">\(\frac{Q-7}{3}\sim (0,1)\)</span>, it <strong>must</strong> be true that:</p>
<ol type="a">
<li><p><span class="math inline">\(E[Q] = 0\)</span></p></li>
<li><p><span class="math inline">\(Var[Q] = 3\)</span></p></li>
<li><p><span class="math inline">\(Q\sim N\)</span></p></li>
<li><p><span class="math inline">\(\sigma_Q=9\)</span></p></li>
</ol>
<p><strong>e) None of the above</strong></p>
</section>
<section id="mc-5" class="level3">
<h3 class="anchored" data-anchor-id="mc-5">MC 5</h3>
<p>In which of the following scenarios did we make a <strong>mistake</strong>?</p>
<p><strong>a) We claimed that <span class="math inline">\(R^2\)</span> and <span class="math inline">\(\bar{R}^2\)</span> should always be the same for a bivariate regression.</strong></p>
<ol start="2" type="a">
<li><p>We claimed that the null hypothesis for a computed statistic should be rejected at a significance level of <span class="math inline">\(\alpha\)</span> if the <span class="math inline">\(100(1-\alpha)\)</span>% confidence interval for that statistic does not include the null value.</p></li>
<li><p>We claimed that the sample standard deviation of X will always be <strong>weakly</strong> greater (<span class="math inline">\(\geq\)</span>) than the standard error of <span class="math inline">\(\bar{X}\)</span> for any sample size.</p></li>
<li><p>We claimed that the total effect of <span class="math inline">\(b_j\)</span> from multivariate OLS of y on <span class="math inline">\(x_2,...,x_k\)</span> will always be equal to the partial effect if <span class="math inline">\(x_j\)</span> is independent from all other regressors.</p></li>
<li><p>None of the above</p></li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>