<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Beauregard, Department of Economics, UC Davis">

<title>ECN 102: Analysis of Economics Data</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="MTFQ2024AK_files/libs/clipboard/clipboard.min.js"></script>
<script src="MTFQ2024AK_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="MTFQ2024AK_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="MTFQ2024AK_files/libs/quarto-html/popper.min.js"></script>
<script src="MTFQ2024AK_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="MTFQ2024AK_files/libs/quarto-html/anchor.min.js"></script>
<link href="MTFQ2024AK_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="MTFQ2024AK_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="MTFQ2024AK_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="MTFQ2024AK_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="MTFQ2024AK_files/libs/bootstrap/bootstrap-8ffd5f67044e5306d9846f29df41dda5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<meta name="description" content="Sample midterm exam answer key for ECN 102.">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="ECN 102 FQ 2024 Sample Midterm AK.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ECN 102: Analysis of Economics Data</h1>
<p class="subtitle lead">Midterm Exam FQ 2024 – Answer Key</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Beauregard, Department of Economics, UC Davis </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div style="text-align: center">
<p>This exam consists of 5 short-answer questions (with sub-parts) and 5 multiple choice questions. You will have a maximum of 50 minutes to complete this exam. No additional time may be taken without prior accommodation. Make sure to read every question thoroughly and carefully. Make sure to answer all parts of all questions completely and fully explain when asked. Show all work to receive full credit.</p>
<p>You may use only the calculators provided by the instructor. Graphing calculators, phone calculators, and other non-standard calculators may not be used. For questions requiring computation, it suffices to express your final answer with 2 significant figures.</p>
<p>There is a formula sheet and scratch paper provided at the end of this exam. You may remove these pages and discard them after the exam. If you plan to use any of these extra pages for your final answers, you must write your name and student ID at the top of each scratch page to ensure it is not lost.</p>
<p>This exam is worth 70 points.</p>
</div>
<p><strong>Solution Guide</strong></p>
<div style="page-break-after: always;"></div>
<section id="question-1-sample-means-10-points" class="level2">
<h2 class="anchored" data-anchor-id="question-1-sample-means-10-points">Question 1: Sample Means [10 points]</h2>
<p>Suppose we know <span class="math inline">\(Q\sim(16,16)\)</span> and we draw 50 samples of size 121 and obtain 50 sample means.</p>
<ol type="a">
<li>How would we properly denote/write the sample mean of <span class="math inline">\(Q\)</span>? (You do not need to explain) [2 points] <span class="math inline">\(\bar{Q}\)</span></li>
</ol>
<p>For the distribution of <strong>sample means</strong> of Q:</p>
<ol start="2" type="a">
<li>What would you expect the population mean to be equal to? [2 points]</li>
</ol>
<p>We know <span class="math inline">\(\mu_{\bar{Q}}=\mu_Q\)</span>, so <span class="math inline">\(\mu_{\bar{Q}}=16\)</span>.</p>
<ol start="3" type="a">
<li>What would you expect the population standard deviation to be equal to? [3 points]</li>
</ol>
<p>We know <span class="math inline">\(\sigma_{\bar{Q}}=\sigma_Q/\sqrt{n}\)</span>, so <span class="math inline">\(\sigma_{\bar{Q}}=\frac{4}{11}\)</span>.</p>
<ol start="4" type="a">
<li>What range would you expect 68% of the sample means of <span class="math inline">\(Q\)</span> to fall under? Explain. [3 points]</li>
</ol>
<p>We expect <span class="math inline">\(\bar{Q}\sim N\)</span> by CLT with <span class="math inline">\(n=121&gt;30\)</span>, so by 68-95-99.7 rule for normal distributions, we expect 68% of sample means to fall between <span class="math inline">\(\pm\sigma\)</span> of the mean: <span class="math inline">\(16\pm\frac{4}{11}\)</span>.</p>
</section>
<section id="question-2-summation-notation-6-points" class="level2">
<h2 class="anchored" data-anchor-id="question-2-summation-notation-6-points">Question 2: Summation Notation [6 points]</h2>
<p>Please calculate the following sums:</p>
<ol type="a">
<li><p>[3 points] <span class="math display">\[\frac13\sum_{i=3}^5(i+2)\]</span> <span class="math inline">\(=\frac{5+6+7}{3}=6\)</span></p></li>
<li><p>[3 points] <span class="math display">\[\sum_{i=1}^3(2^i)\]</span></p></li>
</ol>
<p><span class="math inline">\(=2^1+2^2+2^3=14\)</span></p>
</section>
<section id="question-3-summary-statistics-10-points" class="level2">
<h2 class="anchored" data-anchor-id="question-3-summary-statistics-10-points">Question 3: Summary Statistics [10 points]</h2>
<p>Suppose you obtain the following summary for a sample of data with <code>summarize x, detail</code>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                              x
-------------------------------------------------------------
      Percentiles      Smallest
 1%            1              1
 5%            1              1
10%            1              3       Obs                  11
25%            3              3       Sum of wgt.          11

50%            4                      Mean                  5
                        Largest       Std. dev.      3.162278
75%            8              7
90%            9              8       Variance             10
95%           10              9       Skewness        .238797
99%           10             10       Kurtosis          1.694</code></pre>
</div>
</div>
<ol type="a">
<li>Is the median of this data higher, lower, or equal to the mean? What does this mean for our data? [2 points]</li>
</ol>
<p><span class="math inline">\(\bar{x}&gt;Median;5&gt;4\)</span>. This means we expect our data to be right-skewed.</p>
<ol start="2" type="a">
<li>Interpret the skewness and kurtosis of this data. What do each mean in words? [4 points]</li>
</ol>
<p><span class="math inline">\(Skew&gt;0; Kurt &lt; 3\)</span>. Our data is indeed right-skewed and has thinner tails than a Normal distribution.</p>
<ol start="3" type="a">
<li>Is this data distributed normally? Explain. [4 points]</li>
</ol>
<p>No.&nbsp;As described above, the data is both skewed and has thinner tails. It cannot be normally distributed.</p>
</section>
<section id="question-4-univariate-inference-11-points" class="level2">
<h2 class="anchored" data-anchor-id="question-4-univariate-inference-11-points">Question 4: Univariate Inference [11 points]</h2>
<p>You are given the following from Stata:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>invttail(64,0.05)=1.669013
invttail(64,0.10)=1.2949198
invttail(63,0.05)=1.6694022
invttail(63,0.10)=1.2951343
invttail(62,0.05)=1.6698042
invttail(62,0.10)=1.2953558</code></pre>
</div>
</div>
<p>Suppose you then use the <code>summarize</code> command to obtain the following results for the three variables below. The variables <em>price</em> and <em>weight</em> have been transformed to represent units of <strong>thousands</strong>.</p>
<div class="cell" data-collectcode="true">
<div class="cell-output cell-output-stdout">
<pre><code>(1978 automobile data)

    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
       price |         64    6.266484    3.065138      3.291     15.906
      weight |         64    2.980156    .8023428       1.76       4.84
         mpg |         64    21.57813    6.054789         12         41</code></pre>
</div>
</div>
<ol type="a">
<li>Which of the three variables has the greatest dispersion? Which has the least? [3 points]</li>
</ol>
<p><span class="math inline">\(CV_{price} = \frac{3.07}{6.27}=0.49; CV_{weight}=\frac{0.80}{2.98}=0.27; CV_{mpg}=\frac{6.05}{21.58}=0.28\)</span></p>
<p>Dispersion (most-to-least): <em>price, mpg, weight</em>.</p>
<ol start="2" type="a">
<li>Provide a 90% CI for the mean of <em>mpg</em>. Interpret your answer. [3 points]</li>
</ol>
<p><span class="math inline">\(t^*_{63,0.05}=1.67; CI_{90}= 21.58\pm1.67\left(\frac{6.05}{\sqrt{64}}\right)=(20.32,22.84)\)</span>. We are 90% sure this interval covers the true value of <span class="math inline">\(\mu_{mpg}\)</span>.</p>
<ol start="3" type="a">
<li>The claim is made that the average weight of a car in 1978 was above 2.8 thousand lbs. Using your sample data, test this claim at the 5% significance level. Clearly state your null and alternate hypotheses, your test statistic, and your conclusion. [5 points]</li>
</ol>
<p><span class="math inline">\(H_0: \mu_{weight}\leq2.8\)</span></p>
<p><span class="math inline">\(H_A:\mu_{weight}&gt;2.8\)</span></p>
<p><span class="math inline">\(t^*_{63,0.05}=1.67\)</span>; <span class="math inline">\(t=\frac{2.98-2.8}{0.80/\sqrt{64}}=1.8\)</span></p>
<p>Since <span class="math inline">\(1.8&gt;1.67\)</span>, we reject the null and assert that the average weight of a car in 1978 was indeed above 2.8 thousand pounds.</p>
</section>
<section id="q5-bivariate-data-23-points" class="level2">
<h2 class="anchored" data-anchor-id="q5-bivariate-data-23-points">Q5: Bivariate Data [23 points]</h2>
<ol type="a">
<li>Briefly, what are the four key assumptions about our population bivariate regression model? What do they each mean? [4 points]</li>
</ol>
<ol type="1">
<li><p>Linearity - our true population relationship is linear: <span class="math inline">\(\hat{y_i}=\beta_1+\beta_2x_i\)</span> (or <span class="math inline">\(y_i=\beta_1+\beta_2x_i+u_i\)</span>)</p></li>
<li><p>Unbiasedness - our error term is conditional mean zero/we hit our line in expectation: <span class="math inline">\(E[u_i|x_i]=0\)</span></p></li>
<li><p>Homoskedasticity - our errors are distributed constantly across x: <span class="math inline">\(var[u_i|x_i] = \sigma^2_u\)</span></p></li>
<li><p>Independence - our errors do not influence each other: <span class="math inline">\(u_i\)</span> is independent from <span class="math inline">\(u_j\)</span> for <span class="math inline">\(i\neq j\)</span></p></li>
</ol>
<ol start="2" type="a">
<li>Assuming the four assumptions above hold and our sample is large enough, complete the statement about the distribution of <span class="math inline">\(b_2:b_2\sim\_\_(\_\_,\_\_)\)</span>. Please use Greek letters when appropriate. [3 points]</li>
</ol>
<p><span class="math inline">\(b_2\sim N(\beta_2,\sigma^2_{b_2});\left[\sigma^2_{b_2}=\frac{\sigma^2_u}{\sum_{i=1}^n(x_i-\bar{x})^2}\right]\)</span></p>
<p>Suppose we run the following regression and obtain these results:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Linear regression                               Number of obs     =         64
                                                F(1, 62)          =      93.84
                                                Prob &gt; F          =     0.0000
                                                R-squared         =     0.6350
                                                Root MSE          =     3.6874

------------------------------------------------------------------------------
             |               Robust
         mpg | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
      weight |  -6.013482   .6207753    -9.69   0.000    -7.254394    -4.77257
       _cons |   39.49924   2.099907    18.81   0.000     35.30159     43.6969
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>Write down the estimated linear relationship between <em>weight</em> and <em>mpg</em>. [3 points]</li>
</ol>
<p><span class="math inline">\(\widehat{mpg}=39.50-6.01weight\)</span></p>
<ol start="4" type="a">
<li>What does <code>robust</code> mean in this regression command? Why might we have added this? [3 points]</li>
</ol>
<p>We use robust standard errors to account for possible heteroskedasticity in our errors.</p>
<p>Interpret the t-statistic and p-value for the OLS slope coefficient from the regression output:</p>
<ol start="5" type="a">
<li>What test is this referring to? What are its null and alternate hypotheses? [3 points]</li>
</ol>
<p>This is our test of association between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
<p><span class="math inline">\(H_0: \beta_2=0\)</span></p>
<p><span class="math inline">\(H_A: \beta_2\neq0\)</span></p>
<ol start="6" type="a">
<li>What is the conclusion of this test? [2 points]</li>
</ol>
<p><span class="math inline">\(p=0.000&lt;\alpha=0.05\Rightarrow\)</span> Reject the null. There is a statistically significant association between <em>mpg</em> and <em>weight</em>.</p>
<ol start="7" type="a">
<li>How many degrees of freedom will this test have? Why? [2 points]</li>
</ol>
<p>We will have <span class="math inline">\(n-2\)</span> degrees of freedom because we use 2 computed quantities, <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span>, to find our residual, and the standard error of our residual goes into the standard error of <span class="math inline">\(b_2\)</span>. <span class="math inline">\(df=64-2=62\)</span>.</p>
<ol start="8" type="a">
<li>What would we expect the mpg to be for a car with a weight of 3.5 thousand lbs? [3 points]</li>
</ol>
<p><span class="math inline">\(E[mpg|weight=3.5]=39.50-6.01(3.5)=18.465\)</span></p>
</section>
<section id="multiple-choice-2-points-each" class="level2">
<h2 class="anchored" data-anchor-id="multiple-choice-2-points-each">Multiple Choice [2 points each]</h2>
<p>Only one answer is correct for each question. Choose the best possible answer.</p>
<section id="mc-1" class="level3">
<h3 class="anchored" data-anchor-id="mc-1">MC 1</h3>
<p>A local polling firm plans to conduct phone surveys on issues of concern for voters. They plan to call 45 new households in the county each week and ask respondents how much money they spent on groceries the previous week. This will be repeated for 6 weeks.</p>
<p>This data will be:</p>
<ol type="a">
<li><p>Experimental, categorical, panel</p></li>
<li><p>Experimental, numerical, time-series</p></li>
</ol>
<p><strong>c) Observational, numerical, repeated cross-section</strong></p>
<ol start="4" type="a">
<li><p>Observational, categorical, cross-section</p></li>
<li><p>None of the above</p></li>
</ol>
</section>
<section id="mc-2" class="level3">
<h3 class="anchored" data-anchor-id="mc-2">MC 2</h3>
<p>The OLS estimator:</p>
<ol type="a">
<li><p>minimizes the sum of horizontal deviations of actual data points from the sample regression line</p></li>
<li><p>minimizes the sum of horizontal deviations of actual data points from the population regression line</p></li>
</ol>
<p><strong>c) minimizes the sum of vertical deviations of actual data points from the sample regression line</strong></p>
<ol start="4" type="a">
<li>minimizes the sum of vertical deviations of actual data points from the population regression line</li>
</ol>
</section>
<section id="mc-3" class="level3">
<h3 class="anchored" data-anchor-id="mc-3">MC 3</h3>
<p>For a r.v. X with population mean <span class="math inline">\(\mu\)</span> and population variance <span class="math inline">\(\sigma^2\)</span>, the <em>standard error</em> is:</p>
<ol type="a">
<li>An estimator for the standard deviation of <span class="math inline">\(\mu\)</span></li>
</ol>
<p><strong>b) An estimator for the standard deviation of <span class="math inline">\(\bar{X}\)</span></strong></p>
<ol start="3" type="a">
<li><p>An estimator for the standard deviation of <span class="math inline">\(X\)</span></p></li>
<li><p>Always equal to the sample standard deviation of <span class="math inline">\(X\)</span></p></li>
<li><p>None of the above</p></li>
</ol>
</section>
<section id="mc-4" class="level3">
<h3 class="anchored" data-anchor-id="mc-4">MC 4</h3>
<p>Suppose a r.v. <span class="math inline">\(Z\sim(3,25)\)</span>. We would expect the transformed r.v. <span class="math inline">\(\tilde{Z}=(Z-3)/5\)</span> to be:</p>
<p><strong>a) A z-score</strong></p>
<ol start="2" type="a">
<li><p>Distributed identically to <span class="math inline">\(Z\)</span></p></li>
<li><p>Normally distributed as <span class="math inline">\(n\rightarrow\infty\)</span></p></li>
<li><p>All of the above</p></li>
<li><p>None of the above</p></li>
</ol>
</section>
<section id="mc-5" class="level3">
<h3 class="anchored" data-anchor-id="mc-5">MC 5</h3>
<p>Suppose we regress y on x and obtain the result <span class="math inline">\(\hat{y}=0.33x+1\)</span> with <span class="math inline">\(R^2=0.64\)</span>. If we then regress x on y, we would expect:</p>
<ol type="a">
<li><p>A slope coefficient of 0.33</p></li>
<li><p>A slope coefficient of <span class="math inline">\(0.33^{-1}\approx3\)</span></p></li>
</ol>
<p><strong>c) <span class="math inline">\(\boldsymbol{r_{yx}=0.8}\)</span></strong></p>
<ol start="4" type="a">
<li><p><span class="math inline">\(R^2\neq0.64\)</span></p></li>
<li><p>None of the above</p></li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>