<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Remy Beauregard">

<title>ECN 102: Analysis of Economics Data</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="L4_files/libs/clipboard/clipboard.min.js"></script>
<script src="L4_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="L4_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="L4_files/libs/quarto-html/popper.min.js"></script>
<script src="L4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="L4_files/libs/quarto-html/anchor.min.js"></script>
<link href="L4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="L4_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="L4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="L4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="L4_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<meta name="description" content="Lecture slides 4 for ECN 102.">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="ECN 102 Lecture 4.html"><i class="bi bi-file-slides"></i>RevealJS</a></li><li><a href="ECN 102 Lecture 4.pdf"><i class="bi bi-file-pdf"></i>Beamer</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ECN 102: Analysis of Economics Data</h1>
<p class="subtitle lead">Chapter 4: Univariate Statistical Inference</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Remy Beauregard </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction-inferring-population-parameters" class="level2">
<h2 class="anchored" data-anchor-id="introduction-inferring-population-parameters">Introduction: Inferring Population Parameters</h2>
<p>Previously, we characterized the sample mean <span class="math inline">\(\bar{X}\)</span> as an unbiased and consistent estimator for the population mean <span class="math inline">\(\mu\)</span>. We showed that, under certain conditions, we can expect <span class="math inline">\(\bar{X}\sim N(\mu,\sigma^2/n)\)</span>. However, we usually do not know <span class="math inline">\(\mu\)</span> or <span class="math inline">\(\sigma\)</span>, and want to use the computed sample mean <span class="math inline">\(\bar{x}\)</span> from a <em>single sample</em> to make inferences about our population parameters.</p>
</section>
<section id="example-dataset-stata-auto" class="level2 smaller" data-shrink="20">
<h2 class="smaller anchored" data-shrink="20" data-anchor-id="example-dataset-stata-auto">Example Dataset: Stata Auto</h2>
<p>For example, let’s look at a sample of data given in Stata.</p>
<div class="cell" data-collectcode="true">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">sysuse</span> auto</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="kw">describe</span> <span class="co">// what variables are we working with?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(1978 automobile data)


Contains data from /Applications/Stata/ado/base/a/auto.dta
 Observations:            74                  1978 automobile data
    Variables:            12                  13 Apr 2022 17:45
                                              (_dta has notes)
-----------------------------------------------------------------------------------------------------------------------------------------
Variable      Storage   Display    Value
    name         type    format    label      Variable label
-----------------------------------------------------------------------------------------------------------------------------------------
make            str18   %-18s                 Make and model
price           int     %8.0gc                Price
mpg             int     %8.0g                 Mileage (mpg)
rep78           int     %8.0g                 Repair record 1978
headroom        float   %6.1f                 Headroom (in.)
trunk           int     %8.0g                 Trunk space (cu. ft.)
weight          int     %8.0gc                Weight (lbs.)
length          int     %8.0g                 Length (in.)
turn            int     %8.0g                 Turn circle (ft.)
displacement    int     %8.0g                 Displacement (cu. in.)
gear_ratio      float   %6.2f                 Gear ratio
foreign         byte    %8.0g      origin     Car origin
-----------------------------------------------------------------------------------------------------------------------------------------
Sorted by: foreign</code></pre>
</div>
</div>
</section>
<section id="sample-statistics-for-car-price" class="level2 smaller" data-shrink="20">
<h2 class="smaller anchored" data-shrink="20" data-anchor-id="sample-statistics-for-car-price">Sample Statistics for Car Price</h2>
<p>We see that <span class="math inline">\(\bar{x}=6165.257\)</span> for this sample of <span class="math inline">\(n=74\)</span>. However, we know that we would likely have gotten a different value for <span class="math inline">\(\bar{x}\)</span> if we had (theoretically) drawn a different sample. Do we have enough information to say that average car price <em>in the population</em> in 1978 is above $6000? That it is different from $5500? To answer this, we need more tools for statistical inference.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">summarize</span> price</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
       price |         74    6165.257    2949.496       3291      15906</code></pre>
</div>
</div>
</section>
<section id="computing-the-standard-error" class="level2 smaller" data-shrink="20">
<h2 class="smaller anchored" data-shrink="20" data-anchor-id="computing-the-standard-error">Computing the Standard Error</h2>
<p>The previous summary gives us our obs, mean, and standard deviation for our sample, but we may want our standard error (of the sample mean) computed as well. To have Stata generate this, we use the following command:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">mean</span> price</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean estimation                             Number of obs = 74

--------------------------------------------------------------
             |       Mean   Std. err.     [95% conf. interval]
-------------+------------------------------------------------
       price |   6165.257   342.8719      5481.914      6848.6
--------------------------------------------------------------</code></pre>
</div>
</div>
</section>
<section id="null-and-alternate-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="null-and-alternate-hypotheses">Null and Alternate Hypotheses</h2>
<p>Let us use this information to <em>test our hypothesis</em> that the average car price in the population in 1978 is different than $5500 using our sample. To do this, we first write a <strong>null</strong> and <strong>alternate hypothesis</strong> for the <em>population parameter</em> we are testing: <span class="math display">\[\begin{align*}
H_0: \mu &amp;= 5500 \\
H_A: \mu &amp;\neq 5500
\end{align*}\]</span> The null hypothesis is what we are trying to <em>disprove</em> with our test. If our test is successful, we will <em>reject</em> the null hypothesis. If our test is not successful, we will <em>fail to reject</em> the null hypothesis.</p>
</section>
<section id="one-sided-vs.-two-sided-tests" class="level2">
<h2 class="anchored" data-anchor-id="one-sided-vs.-two-sided-tests">One-Sided vs.&nbsp;Two-Sided Tests</h2>
<p>Because we are testing whether or not our population mean <span class="math inline">\(\mu\)</span> is <em>different</em> from $5500, we call this a <strong>two-sided</strong> hypothesis test. We could reject our null hypothesis because <span class="math inline">\(\bar{x}\)</span> is significantly higher or lower than $5500, so we are testing on both sides.</p>
<p>If instead we were testing the claim that average population car price was <em>above</em> $6000, this would be a <strong>one-sided</strong> hypothesis test, as we are only rejecting the null for values significantly above $6000 but not below. Then, our hypotheses would be <span class="math display">\[\begin{align*}
H_0: \mu &amp;\leq 6000 \\
H_A: \mu &amp;&gt; 6000
\end{align*}\]</span></p>
</section>
<section id="standardizing-the-sample-mean-z-score" class="level2">
<h2 class="anchored" data-anchor-id="standardizing-the-sample-mean-z-score">Standardizing the Sample Mean: Z-Score</h2>
<p>Previously, we had transformed our sample mean r.v. <span class="math inline">\(\bar{X}\)</span> into a standard normal (with <span class="math inline">\(n&gt;30\)</span>) by: <span class="math display">\[Z=\frac{\bar{X}-\mu}{\sigma/\sqrt{n}}\sim N(0,1)\]</span> We called this distribution <span class="math inline">\(N(0,1)\)</span> the <em>standard normal distribution</em>. This transformation is useful because we know (or can calculate) exactly the probability of lying above or below any z-score value, or conversely the z-score value corresponding to any probability mass of data.</p>
</section>
<section id="the-normal-distribution-68-95-99.7-rule" class="level2">
<h2 class="anchored" data-anchor-id="the-normal-distribution-68-95-99.7-rule">The Normal Distribution: 68-95-99.7 Rule</h2>
<p>The normal distribution has a rule of thumb associated with it: we know that roughly 68% of data will lie within one standard deviation of the mean, 95% will lie within 2 standard deviations, and 99.7% will lie within three standard deviations.</p>
<p>For any given z-score value, we can compute the exact probability mass of data that lies to the left or right of a given value. Since the (standard) normal distribution is symmetric, we can perfectly fold the distribution in half over the y-axis.</p>
</section>
<section id="standard-normal-density-plot" class="level2">
<h2 class="anchored" data-anchor-id="standard-normal-density-plot">Standard Normal Density Plot</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="L4normal.png" class="img-fluid figure-img" style="width:100.0%" alt="Plot of the standard normal density function. The x-axis shows z-scores from −4 to 4 with tick marks at each integer, and the y-axis shows density. The symmetric bell-shaped curve is centered at zero and labeled 'Standard normal density'."></p>
<figcaption>Standard normal density curve.</figcaption>
</figure>
</div>
</section>
<section id="normal-probabilities-in-stata" class="level2">
<h2 class="anchored" data-anchor-id="normal-probabilities-in-stata">Normal Probabilities in Stata</h2>
<p>We can use the code below to get the probability mass to the <em>left</em> of any z-score, or inversely the z-score associated with a probability mass to its left of some amount.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="fu">normal</span>(1) <span class="co">// Pr(Z&lt;1)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="fu">invnormal</span>(0.975) <span class="co">// z:Pr(Z&lt;z)=97.5%</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>.84134475

1.959964</code></pre>
</div>
</div>
<p>We see from this that roughly 84.1% of data in the standard normal distribution lies below a z-score of 1, and a z-score of roughly 1.96 has 97.5% of the probability mass to its left.</p>
</section>
<section id="di-normal1-left-tail-probability-plot" class="level2">
<h2 class="anchored" data-anchor-id="di-normal1-left-tail-probability-plot">di normal(1): Left-Tail Probability Plot</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="L4norm.png" class="img-fluid figure-img" style="width:100.0%" alt="Standard normal density curve with the area to the left of z=1 shaded in dark navy, illustrating Pr(Z<1). The x-axis is labeled at −4, 0, 1, and 4. The plot title reads 'di normal(1)' and the subtitle shows the computed probability value."></p>
<figcaption>Standard normal density with left-tail area shaded up to z=1.</figcaption>
</figure>
</div>
</section>
<section id="di-invnormal0.975-inverse-normal-plot" class="level2">
<h2 class="anchored" data-anchor-id="di-invnormal0.975-inverse-normal-plot">di invnormal(0.975): Inverse Normal Plot</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="L4invnorm.png" class="img-fluid figure-img" style="width:100.0%" alt="Standard normal density curve with the area to the left of z≈1.96 shaded in dark navy, illustrating invnormal(0.975). The x-axis is labeled at −4, 0, and 4. The plot title reads 'di invormal(0.975)' and the subtitle shows z≈1.96 such that Pr(Z<z)=0.975."></p>
<figcaption>Standard normal density with 97.5% of area shaded up to z≈1.96.</figcaption>
</figure>
</div>
</section>
<section id="recap-stata-normal-functions" class="level2">
<h2 class="anchored" data-anchor-id="recap-stata-normal-functions">Recap: Stata Normal Functions</h2>
<p>To recap:</p>
<ul>
<li><p><code>di normal(z)</code> gives us the probability mass to the left of a given z-score</p></li>
<li><p><code>di invnormal(p)</code> gives us the z-score such that the probability mass to the left of that z-score is equal to <span class="math inline">\(p\)</span></p></li>
<li><p>“di” is just Stata for “display”</p></li>
</ul>
</section>
<section id="limitation-estimating-the-standard-deviation" class="level2">
<h2 class="anchored" data-anchor-id="limitation-estimating-the-standard-deviation">Limitation: Estimating the Standard Deviation</h2>
<p>Unfortunately, all of the work we just did above relies on a standard normal distribution and z-scores, which requires us to know <span class="math inline">\(\sigma/\sqrt{n}\)</span>, the population standard deviation of <span class="math inline">\(\bar{X}\)</span>. The best we can do, however, is estimate <span class="math inline">\(\sigma/\sqrt{n}\)</span> using <span class="math inline">\(s/\sqrt{n}\)</span>, our standard error for <span class="math inline">\(\bar{X}\)</span>.</p>
<p>When we replace <span class="math inline">\(\sigma/\sqrt{n}\)</span> with <span class="math inline">\(s/\sqrt{n}\)</span> in our z-score formula, we get a distribution that is <em>almost</em> standard normal but not exactly.</p>
</section>
<section id="the-t-distribution" class="level2">
<h2 class="anchored" data-anchor-id="the-t-distribution">The T Distribution</h2>
<p>Instead, we now have <span class="math display">\[T=\frac{\bar{X}-\mu}{S/\sqrt{n}}\]</span></p>
<p>The T distribution is a bit more complicated that the standard normal, as it depends on our <em>degrees of freedom</em> for its shape (symmetric and close to normal, but with kurtosis <span class="math inline">\(&gt;3\)</span>). We say <span class="math inline">\(T\sim T(n-1)\)</span>, where <span class="math inline">\(n-1\)</span> represents our degrees of freedom.</p>
<p>. . .</p>
<p>Note: every T distribution with the same degrees of freedom will have the same shape. Thus, we can fully characterize the distribution we are working with by computing <span class="math inline">\(n-1\)</span>. For the standard normal distribution this was not the case - the standard normal distribution looks exactly the same for any/all values of <span class="math inline">\(n\)</span> (does not depend on degrees of freedom).</p>
</section>
<section id="the-t-statistic" class="level2">
<h2 class="anchored" data-anchor-id="the-t-statistic">The T-Statistic</h2>
<p>For an observed sample mean <span class="math inline">\(\bar{x}\)</span>, we can construct a <strong>t-statistic</strong> <span class="math display">\[t=\frac{\bar{x}-\mu_0}{se(\bar{x})}=\frac{\bar{x}-\mu_0}{s/\sqrt{n}}\sim T(n-1)\]</span> whenever <span class="math inline">\(n&gt;30\)</span>. To compute the t-statistic for a given null hypothesis, we plug in the parameter value assumed under the null, <span class="math inline">\(\mu_0\)</span>. From our previous null hypothesis, <span class="math inline">\(\mu_0=5500\)</span>.</p>
<p>. . .</p>
<p>Thus, we can finally compute the t-statistic from our previous test: <span class="math display">\[t=\frac{6165.257-5500}{342.8719}=1.94\text{ with }df=n-1=73\]</span></p>
</section>
<section id="evaluating-the-t-statistic-p-values-and-significance" class="level2">
<h2 class="anchored" data-anchor-id="evaluating-the-t-statistic-p-values-and-significance">Evaluating the T-Statistic: P-Values and Significance</h2>
<p>We have found that <span class="math inline">\(t=1.94\)</span> for our earlier hypothesis test for car price. However, we need a threshold to compare this value to to decide whether we can reject our null hypothesis.</p>
<p>. . .</p>
<p>Computing a z- or t-statistic from a distribution with a known density function means we can compute the probability of drawing a statistic at least as large from that distribution. We call this quantity our <strong>p-value</strong>: the probability of drawing a [t-]statistic <em>at least as large</em> as 1.94 <em>if we were to draw another sample and compute a new [t-]statistic</em> <strong>under the null distribution</strong>.</p>
<p>. . .</p>
<p>We set a threshold for this likelihood value we call the <strong>significance level</strong>, denoted by <span class="math inline">\(\alpha\)</span>. In Economics, we commonly take <span class="math inline">\(\alpha=0.05\)</span>, or a <span class="math inline">\(\frac{1}{20}\)</span> chance being low enough to reject our null hypothesis. However, we may alternatively use <span class="math inline">\(\alpha=0.1\)</span> or <span class="math inline">\(\alpha=0.01\)</span>.</p>
</section>
<section id="courtroom-analogy-hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="courtroom-analogy-hypothesis-testing">Courtroom Analogy: Hypothesis Testing</h2>
<p>Thought experiment: someone on trial. In the US, we assume defendants are innocent until proven guilty. Thus, our hypotheses in the courtroom for the outcome of a trial <span class="math inline">\(\theta\)</span> are: <span class="math display">\[H_0:\theta=\text{innocent}\]</span> <span class="math display">\[H_A:\theta\neq\text{innocent}\]</span></p>
<p>. . .</p>
<p>We assess the evidence against a defendant assuming they are innocent and compute the probability that an innocent person would have as much evidence against them as our defendant does (p-value). If the probability of an innocent person having this much evidence against them is below 5% or <span class="math inline">\(\frac{1}{20}\)</span>, we reject the null (innocence) and assert that the defendant is guilty (alternate).</p>
<p>. . .</p>
<p>However, being found not guilty does not mean there is <em>no evidence</em> against our defendant. It simply means we have <em>insufficient evidence</em> to prove their guilt or <em>fail to reject the null</em>.</p>
</section>
<section id="p-value-vs.-critical-value-approaches" class="level2">
<h2 class="anchored" data-anchor-id="p-value-vs.-critical-value-approaches">P-Value vs.&nbsp;Critical Value Approaches</h2>
<p>There are two ways of comparing our computed t-statistic to our significance level. We can either:</p>
<ul>
<li><p>Convert our t-statistic into the p-value associated with that t-statistic and compare that to <span class="math inline">\(\alpha=0.05\)</span>. A p-value <em>less than</em> <span class="math inline">\(\alpha\)</span> means it is <em>very unlikely</em> that we drew such a statistic under the <strong>null distribution</strong> and thus we reject our null hypothesis.</p></li>
<li><p>Convert our significance level <span class="math inline">\(\alpha\)</span> into a t-<strong>critical value</strong>, the t-score (<span class="math inline">\(t^*_{df}\)</span>) at which <span class="math inline">\(\Pr(T&gt;t^*_{df})=\alpha\)</span>. If our computed t-statistic is <em>larger</em> than our critical value, we again say that it is <em>very unlikely</em> that we drew such a statistic under the <strong>null distribution</strong> and thus we reject our null hypothesis.</p></li>
</ul>
</section>
<section id="stata-ttail-and-invttail-functions" class="level2">
<h2 class="anchored" data-anchor-id="stata-ttail-and-invttail-functions">Stata: ttail and invttail Functions</h2>
<p>Like before, Stata gives us functions to compute p-values and t-critical values:</p>
<ul>
<li><p><code>di ttail(df,t)</code> gives us the probability mass to the RIGHT of a given t-stat for <span class="math inline">\(df=n-1\)</span></p></li>
<li><p><code>di invttail(df,α)</code> gives us the t critical value <span class="math inline">\(t^*_{df}\)</span> such that the probability mass to the RIGHT of that t-stat is equal to <span class="math inline">\(\alpha\)</span> for <span class="math inline">\(df=n-1\)</span></p></li>
</ul>
<p><strong>Hint</strong>: in exams, it is typical to provide a table of invttail() output for a range of significance values and the degrees of freedom of a sample. Thus, the <strong>p-value</strong> approach for hypothesis testing is less common on exams than the <strong>critical value</strong> approach.</p>
</section>
<section id="one-sided-vs.-two-sided-critical-values" class="level2">
<h2 class="anchored" data-anchor-id="one-sided-vs.-two-sided-critical-values">One-Sided vs.&nbsp;Two-Sided Critical Values</h2>
<p>However, we must now again consider one- versus two-sided tests. In a one-sided test, we are only testing above OR below a given point, so we can use invttail(df,<span class="math inline">\(\alpha\)</span>) as normal. In two-sided tests, however, we are testing both the upper and lower tails of the distribution simultaneously. Thus, for two-sided tests we need to compute <span class="math inline">\(t^*_{df}:\Pr(|T|&gt;|t^*_{df}|)=\alpha\)</span> or equivalently <span class="math inline">\(t^*_{df}:\Pr(T&gt;t^*_{df})=\alpha/2\)</span> due to symmetry of our t-distribution.</p>
<p>Remember, our t-distribution is symmetric, so it must be true that <span class="math inline">\(\Pr(T &gt; t^*_{df}) = \Pr(T &lt; -t^*_{df})\)</span>. Also, since our probabilities must sum to 1, <span class="math inline">\(\Pr(T \geq t^*_{df}) = 1-\Pr(T &lt; t^*_{df})\)</span>.</p>
</section>
<section id="t-distribution-tail-regions" class="level2">
<h2 class="anchored" data-anchor-id="t-distribution-tail-regions">T Distribution: Tail Regions</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tdist.png" class="img-fluid figure-img" style="width:100.0%" alt="Diagram of the t-distribution showing critical regions for hypothesis testing. The symmetric bell-shaped curve has shaded tail areas illustrating rejection regions for one-sided and two-sided tests, with labeled critical values on the horizontal axis."></p>
<figcaption>T distribution showing one-sided and two-sided rejection regions.</figcaption>
</figure>
</div>
</section>
<section id="practice-t-distribution-probabilities" class="level2">
<h2 class="anchored" data-anchor-id="practice-t-distribution-probabilities">Practice: T-Distribution Probabilities</h2>
<p>Let’s practice <code>ttail()</code> and <code>invttail()</code> for a few one- and two-sided test examples with <span class="math inline">\(n=39\)</span>:</p>
<ul>
<li><p><span class="math inline">\(\Pr(T &gt; 1.6)\)</span></p></li>
<li><p><span class="math inline">\(\Pr(|T| &gt; 0.8)\)</span></p></li>
<li><p><span class="math inline">\(\Pr(T &lt; 1.3)\)</span></p></li>
<li><p><span class="math inline">\(\Pr(|T|&lt; 1)\)</span></p></li>
<li><p><span class="math inline">\(t^*_{38}:\Pr(T&gt;t^*_{38})=0.025\)</span></p></li>
<li><p><span class="math inline">\(t^*_{38}:\Pr(|T|&gt;|t^*_{38}|)=0.1\)</span></p></li>
<li><p><span class="math inline">\(t^*_{38}:\Pr(T&lt;t^*_{38})=0.3\)</span></p></li>
</ul>
</section>
<section id="practice-solutions-t-distribution-probabilities" class="level2">
<h2 class="anchored" data-anchor-id="practice-solutions-t-distribution-probabilities">Practice Solutions: T-Distribution Probabilities</h2>
<p>Let’s practice <code>ttail()</code> and <code>invttail()</code> for a few one- and two-sided test examples with <span class="math inline">\(n=39\)</span> (<span class="math inline">\(df=n-1=38\)</span>):</p>
<ul>
<li><p><span class="math inline">\(\Pr(T &gt; 1.6)\)</span>: <code>di ttail(38,1.6)</code></p></li>
<li><p><span class="math inline">\(\Pr(|T| &gt; 0.8)\)</span>: <code>di 2*ttail(38,0.8)</code></p></li>
<li><p><span class="math inline">\(\Pr(T &lt; 1.3)\)</span>: <code>di 1-ttail(38,1.3)</code></p></li>
<li><p><span class="math inline">\(\Pr(|T|&lt; 1)\)</span><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>: <code>di 1-2*ttail(38,1)</code></p></li>
<li><p><span class="math inline">\(t^*_{38}:\Pr(T&gt;t^*_{38})=0.025\)</span>: <code>di invttail(38,0.025)</code></p></li>
<li><p><span class="math inline">\(t^*_{38}:\Pr(|T|&gt;|t^*_{38}|)=0.1\)</span>: <code>di invttail(38,0.1/2)</code></p></li>
<li><p><span class="math inline">\(t^*_{38}:\Pr(T&lt;t^*_{38})=0.3\)</span>: <code>di invttail(38, 1-0.3)</code></p></li>
</ul>
</section>
<section id="hypothesis-test-result-car-price" class="level2 smaller" data-shrink="20">
<h2 class="smaller anchored" data-shrink="20" data-anchor-id="hypothesis-test-result-car-price">Hypothesis Test Result: Car Price</h2>
<p>Finally, we are ready to answer our hypothesis test from the beginning. We computed <span class="math inline">\(t=1.94\)</span> for <span class="math inline">\(n=74\)</span> with hypotheses <span class="math display">\[\begin{align*}
H_0: \mu &amp;= 5500 \\
H_A: \mu &amp;\neq 5500
\end{align*}\]</span> We compute our critical value <span class="math inline">\(t^*_{df,\alpha/2}\)</span> for <span class="math inline">\(\alpha=0.05\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="fu">invttail</span>(74-1,0.05/2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.9929971</code></pre>
</div>
</div>
<p>and find <span class="math inline">\(t^*_{73,0.025}=1.993\)</span>. Since <span class="math inline">\(1.94&lt;1.993\)</span>, we <em>fail to reject</em> our null hypothesis that <span class="math inline">\(\mu=5500\)</span>. However, importantly, <em>we do not accept the null</em>. We simply say that we fail to reject the null <em>for this particular sample</em>.</p>
</section>
<section id="recap-critical-value-and-p-value-methods" class="level2">
<h2 class="anchored" data-anchor-id="recap-critical-value-and-p-value-methods">Recap: Critical Value and P-Value Methods</h2>
<p>To recap: two-sided hypothesis tests require us to divide <span class="math inline">\(\alpha\)</span> by 2 when we are using the critical value approach, because the probability mass is being split equally between the upper and lower tails of the distribution. For a one-sided test, all the mass is in either the upper or lower tail, so we can take <span class="math inline">\(\alpha\)</span> as given.</p>
<p>The p-value approach converts our t-statistic into its p-value and rejects the null if that value is less than our significance level. The critical value approach converts <span class="math inline">\(\alpha\)</span> or <span class="math inline">\(\alpha/2\)</span> into a critical value <span class="math inline">\(t^*_{df,\alpha[/2]}\)</span> and rejects the null if our computed t-statistic is larger (in absolute value) than our critical value.</p>
</section>
<section id="confidence-intervals-concept" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals-concept">Confidence Intervals: Concept</h2>
<p>Finally, <strong>confidence intervals</strong> (CIs) are the inverse of two-sided hypothesis tests. If a two-sided test gives the chance that we draw our computed statistic under the null distribution, a confidence interval gives a range of values around our computed statistic that we can be some % sure contains our true parameter value.</p>
<p>. . .</p>
<p>While it is unknown, our true population parameter <span class="math inline">\(\mu\)</span> is some fixed value and not probabilistic. Thus, it is incorrect to say “<span class="math inline">\(\mu\)</span> has an X% chance of lying in this range”. Instead, we say “This range has an X% chance of <em>including</em>/<em>covering</em> the true value of <span class="math inline">\(\mu\)</span>”.</p>
<p>. . .</p>
<p>Since our confidence interval depends on <span class="math inline">\(se(\bar{x})\)</span> and <span class="math inline">\(se(\bar{x})\)</span> in turn shrinks with <span class="math inline">\(n\)</span>, our confidence interval will <em>shrink</em> as <span class="math inline">\(n\rightarrow\infty\)</span>. Intuitively, a 90% CI will also be narrower than a 95% CI, as it covers fewer possible values for <span class="math inline">\(\mu\)</span>.</p>
</section>
<section id="confidence-interval-formula" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-formula">Confidence Interval Formula</h2>
<p>The confidence interval formula uses all the same components as our t-statistic, but in a slightly different order. The <span class="math inline">\(100(1-\alpha)\)</span>% confidence interval for <span class="math inline">\(\mu\)</span> given some <span class="math inline">\(\bar{x}, n, se(\bar{x})\)</span> is given as <span class="math display">\[\bar{x}\pm \underbrace{t^*_{n-1,\alpha/2}\times se(\bar{x})}_{\text{"margin of error"}}\]</span> This range has a <span class="math inline">\(100(1-\alpha)\)</span>% chance of containing the true population parameter value <span class="math inline">\(\mu\)</span>. When reporting a CI, we need to always give two values <span class="math inline">\((lower,upper)\)</span>.</p>
</section>
<section id="confidence-intervals-as-inverse-hypothesis-tests" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals-as-inverse-hypothesis-tests">Confidence Intervals as Inverse Hypothesis Tests</h2>
<p>We can demonstrate the claim that two-sided hypothesis tests are the inverse of confidence intervals below: <span class="math display">\[\underbrace{t_{n-1}=\frac{\bar{x}-\mu_0}{se(\bar{x})}}_{\text{2-sided t-test}} \leftrightarrow\underbrace{\bar{x}\pm t^*_{n-1,\alpha/2}\times se(\bar{x})=(\mu_0^{smallest},\mu_0^{largest})}_{100(1-\alpha)\%\text{ confidence interval}}\]</span> (Formal proof ch.&nbsp;4.3.3, pg. 66-67)</p>
<p>Our 2-sided t-test gives us the probability of getting a t-statistic at least as large as the one we got (in absolute value) under the null hypothesis assumption <span class="math inline">\(\mu_0\)</span>. A confidence interval will instead give us the smallest and largest values for <span class="math inline">\(\mu_0\)</span> we could assume under the null hypothesis for which we would <em>fail to reject the null</em>.</p>
</section>
<section id="key-equivalences-tests-and-confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="key-equivalences-tests-and-confidence-intervals">Key Equivalences: Tests and Confidence Intervals</h2>
<p><strong>Very important</strong>:</p>
<p><span class="math inline">\(\Rightarrow\)</span> Since our p-value and critical value approaches are inverse operations of each other, <em>both should always give us the same conclusion</em> of whether we reject or fail to reject our null hypothesis.</p>
<p><span class="math inline">\(\Rightarrow\)</span> Similarly, since our 2-sided hypothesis test and confidence interval calculation are inverse operations of each other, <em>both should always give us the same conclusion</em> of whether we reject or fail to reject our null hypothesis. When we reject a two-sided hypothesis test for some <span class="math inline">\(\mu_0,\bar{x},n,se(\bar{x})\)</span>, that <span class="math inline">\(\mu_0\)</span> should also fall <em>outside</em> the range of our <span class="math inline">\(100(1-\alpha)\)</span>% confidence interval for <span class="math inline">\(\mu\)</span>.</p>
</section>
<section id="interpreting-and-choosing-confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-and-choosing-confidence-intervals">Interpreting and Choosing Confidence Intervals</h2>
<p>How do we interpret CIs? We may think that we want the largest CI possible to be as sure as we can that we are covering the true value of <span class="math inline">\(\mu\)</span>. However, this is misguided: the range <span class="math inline">\((-\infty,\infty)\)</span> has a 100% chance of covering all possible values of <span class="math inline">\(\mu\)</span> for any and all distributions, but this is not informative for statistical inference. We typically select a 90% or 95% CI in Economics. Stata will automatically report a 95% CI for <span class="math inline">\(\mu\)</span> with the <em>mean</em> command.</p>
<p>For a single sample (and a single <span class="math inline">\(\bar{x}\)</span>), our CI will have a <span class="math inline">\(100(1-\alpha)\)</span>% chance of covering the true value of <span class="math inline">\(\mu\)</span>. If we repeatedly resample a large number of times and compute an <span class="math inline">\(\bar{x}\)</span> and CI for each sample, we expect that <span class="math inline">\(100(1-\alpha)\)</span>% of those CIs <em>will</em> cover the true value of <span class="math inline">\(\mu\)</span>.</p>
</section>
<section id="ci-for-car-price" class="level2 smaller" data-shrink="20">
<h2 class="smaller anchored" data-shrink="20" data-anchor-id="ci-for-car-price">95% CI for Car Price</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">mean</span> price</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean estimation                             Number of obs = 74

--------------------------------------------------------------
             |       Mean   Std. err.     [95% conf. interval]
-------------+------------------------------------------------
       price |   6165.257   342.8719      5481.914      6848.6
--------------------------------------------------------------</code></pre>
</div>
</div>
<p>95% CI for <span class="math inline">\(\mu_{price}=(5481.914,6848.6)\)</span>. This range has a 95% chance of including the true population value of <span class="math inline">\(\mu_{price}\)</span>.</p>
<p>The value we assumed under the null above, $5500, falls <em>within</em> this range, <span class="math inline">\(5500\in(5481.914,6848.6)\)</span>, so it should not be surprising that we <em>failed to reject the null</em> for our 2-sided t-test above.</p>
</section>
<section id="end-of-lecture-material" class="level1">
<h1>End of Lecture Material</h1>
<section id="knowledge-check-4" class="level2">
<h2 class="anchored" data-anchor-id="knowledge-check-4">Knowledge Check 4</h2>
<p>Suppose we compute <span class="math inline">\(\bar{x}=4.5\)</span> and <span class="math inline">\(s_{\bar{x}}=1\)</span> for a sample of data and <span class="math inline">\(t^*_{n-1,0.05}=1.69\)</span> and <span class="math inline">\(t^*_{n-1,0.025}=2.03\)</span> for our sample size <span class="math inline">\(n\)</span>.</p>
<p>Test the claims that:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math inline">\(\mu\neq4\)</span></p>
</div><div class="column" style="width:50%;">
<p><span class="math inline">\(\mu&gt;2\)</span></p>
</div>
</div>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>We should expect this to be close to 68% based on our 68-95-99.7 rule.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>